- app/models/game.rb
Tell active record to look for a class `User` for the buyer relation
> Specify class name for buyer relation

- db/seeds.rb
> added first user seed for test purpose

- app/models/game.rb
- app/models/user.rb
Add has_many on user
Add validation on games
> add relationship to user model and validation to game model

- app/controllers/games_controller.rb
- app/views/games/create.html.erb
- app/views/games/destroy.html.erb
- app/views/games/index.html.erb
- app/views/games/new.html.erb
- app/views/games/show.html.erb
- config/routes.rb
- db/migrate/20190218171539_add_picture_to_games.rb
- test/controllers/games_controller_test.rb
We forgot picture on games so I added it
> Add picture to games

- app/controllers/reviews_controller.rb
- app/views/reviews/create.html.erb
- app/views/reviews/index.html.erb
- app/views/reviews/new.html.erb
- config/routes.rb
- test/controllers/reviews_controller_test.rb
Added CRUD actions and routes to Reviews
Work remaining: Finalize view once user/user_id#show is done
> Review crud

- app/views/games/index.html.erb
- app/views/layouts/application.html.erb
- db/schema.rb
- db/seeds.rb
end bugfix
seeds for games
and working games#index
> Working on game#index1

- config/routes.rb
ok i manage the probleme with the "s" route
> profile_root_s

- app/controllers/profiles_controller.rb
- app/views/profiles/show.html.erb
- config/routes.rb
- test/controllers/profiles_controller_test.rb
i generate profiles controller and view and the routes
> add_profiles_controller

- app/views/games/index.html.erb
- db/seeds.rb
change the seed
change in the index.html.erb
> Game image and user image for each game in index

- app/views/shared/_navbar.html.erb
Navbar
change path for "Add a new game"
change path for "Find a game"
change path for "Profile"
> navbar links path modified

- app/views/shared/_navbar.html.erb
> we can display the user photo

- app/controllers/profiles_controller.rb
- app/views/profiles/edit.html.erb
- app/views/shared/_navbar.html.erb
- config/routes.rb
my_profile & changed some things on the navbar
> Setting my profile

- app/models/user.rb
- app/views/profiles/show.html.erb
- db/seeds.rb
Change on user has many relations to create sold_games and bought_games
change seeds to test transactions
transaction display in profile is done
> Transaction display on profile

- app/controllers/games_controller.rb
- app/views/games/confirmed.html.erb
Confirmation after payment is done
> confirmation page after payment

- app/controllers/games_controller.rb
- app/views/games/index.html.erb
only displaying games unsold on index page
> Games index

- app/controllers/reviews_controller.rb
- app/models/review.rb
- app/views/profiles/show.html.erb
- app/views/reviews/new.html.erb
- db/migrate/20190220164850_add_receiver_to_reviews.rb
- db/schema.rb
- db/seeds.rb
List of changes:
- NEW MIGRATION DONE - reviews table new column -> receiver_id
DON'T FORGET TO RUN RAILS DB:MIGRATE AFTER YOUR NEXT PULL FROM MASTER
- Change relation for receiver
- Implement of add review button in my_profile view
- Definition of relationships of reviews
- Modification of method create in review controller
- Change seeds to test feature
> Review link to transaction

- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/layouts/_index.scss
> fixed navbar + margin top on container class to respect navbar

- app/views/profiles/show.html.erb
Changes:
- add to be sold games in profile view
> add games to be sold in profile

- app/assets/javascripts/application.js
- app/assets/stylesheets/pages/_payment.scss
- app/controllers/games_controller.rb
- app/views/games/payment.html.erb
I implemented the payment method + confirmed payment
+ payment form (fake)
> Payment method

- app/assets/stylesheets/components/_card.scss
- app/views/games/index.html.erb
- app/views/games/show.html.erb
- db/seeds.rb
> Display prices

- app/assets/stylesheets/components/_card.scss
- app/javascript/packs/application.js
- package.json
- yarn.lock
problem fixed with the p text card
> cards_final_game#index

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/pages/_profile.scss
- app/controllers/reviews_controller.rb
- app/models/user.rb
- app/views/profiles/show.html.erb
Change on profile page style
change on relation on user model has many review foreign key changed
> my profile style done, reviews changed to correct user

- app/controllers/games_controller.rb
- app/views/profiles/show.html.erb
Transaction date added to my profile view
> transaction date added + formated

- app/assets/stylesheets/components/_alert.scss
- app/assets/stylesheets/components/_footer.scss
- app/assets/stylesheets/components/_index.scss
- app/controllers/games_controller.rb
- app/controllers/users_controller.rb
- app/javascript/plugins/init_mapbox.js
- app/views/games/index.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_flashes.html.erb
- db/seeds.rb
> Login Alerts

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/pages/_payment.scss
- app/controllers/games_controller.rb
- app/views/devise/sessions/new.html.erb
- app/views/games/confirmed.html.erb
- app/views/games/index.html.erb
- app/views/games/payment.html.erb
- app/views/games/show.html.erb
- app/views/layouts/application.html.erb
- app/views/profiles/show.html.erb
container on all pages and added some picto on profile page
> Container pages
